local test = require("santoku.test")
local err = require("santoku.error")
local assert = err.assert
local spans = require("santoku.spans")
local ivec = require("santoku.ivec")
local ner = require("santoku.learn.ner")
local tbl = require("santoku.table")
local teq = tbl.equals

test("ner: type_labels", function ()
  local C = spans.create({ "s", "e" })
  C:push(0, 2):push(0, 5):push(2, 5):doc()
  local G = spans.create({ "s", "e", "ty" })
  G:push(0, 2, 1):push(2, 5, 3):doc()
  local lab = C:type_labels(G, 4)
  assert(teq(lab:table(), { 1, 4, 3 }))   -- (0,5) matches no gold -> reject(=4)
end)

test("ner: miss_report", function ()
  local gaz = spans.create({ "s", "e", "ty" })
  gaz:doc()                                -- one empty doc
  local bio = spans.create({ "s", "e", "ty" })
  bio:push(0, 2, 0):push(6, 8, 0):doc()
  local gold = spans.create({ "s", "e", "ty" })
  gold:push(0, 2, 1):push(5, 9, 2):doc()
  local m = ner.miss_report({ gaz = gaz, bio = bio, gold = gold, n_types = 4 })
  assert(m.gold == 2)
  assert(m.covered == 0)
  assert(m.wrong_type == 1)                -- bio (0,2) exact boundary, wrong type for gold (0,2,1)
  assert(m.under == 1 and m.under_bio == 1 and m.under_gaz == 0)  -- bio (6,8) inside gold (5,9)
  assert(m.under_by_type[2] == 1)
end)

test("ner: decode_report", function ()
  local C = spans.create({ "s", "e" })
  C:push(0, 2):push(5, 9):push(3, 4):doc()
  local G = spans.create({ "s", "e", "ty" })
  G:push(0, 2, 1):push(5, 9, 2):doc()
  local pred = ivec.create({ 1, 4, 0 })    -- stride 1: cand0 -> type1, cand1 -> reject(4), cand2 unused
  local r = ner.decode_report({ cand = C, gold = G, pred = pred, pred_stride = 1, n_types = 4 })
  assert(r.gold == 2 and r.in_pool == 2 and r.not_in_pool == 0)
  assert(r.correct == 1 and r.false_reject == 1 and r.mistype == 0)
  assert(r.reject_by_type[2] == 1)
end)
